
version: '3.8'

services:
  gruasucabordersms:
    image: gruasucabordersms:latest
    build:
      context: .
      dockerfile: GruasUcabOrdersMS/Dockerfile
    ports:
      - "5101:5101"
      - "7057:7057"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DBConnectionString=Host=labs-dbservices01.ucab.edu.ve;Database=GruasUcabOrderMS;Port=5432;Username=gmartinez;Password=123456;
      - ASPNETCORE_URLS=http://+:5101;https://+:7057
      - RabbitMQ__HostName=https://shrimp-01.rmq.cloudamqp.com
      - RabbitMQ__UserName=pybwtysn
      - RabbitMQ__Password=7RWjGrcK8hYn0CQlz4Uuak6MjqlRMgZg

    networks:
      - mynetwork
    
    command: >
      sh -c "dotnet ef database update --no-build && dotnet GruasUcabOrdersMS.dll"

networks:
  mynetwork:
    driver: bridge