
version: '3.8'

services:
  gruasucabordersms:
    image: gruasucabordersms:latest
    build:
      context: .
      dockerfile: GruasUcabOrdersMS/Dockerfile
    ports:
      - "5101:5101"
      - "7057:7057"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DBConnectionString=Host=labs-dbservices01.ucab.edu.ve;Database=GruasUcabOrderMS;Port=5432;Username=gmartinez;Password=123456;
      - ASPNETCORE_URLS=http://+:5101;https://+:7057
      - Rabbit__HostName=amqps://pybwtysn:7RWjGrcK8hYn0CQlz4Uuak6MjqlRMgZg@shrimp-01.rmq.cloudamqp.com/pybwtysn
      - Rabbit__UserName=pybwtysn
      - Rabbit__Password=7RWjGrcK8hYn0CQlz4Uuak6MjqlRMgZg
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AllowedHosts=*
      - ApiKey__Google=AIzaSyCUWtvL5DPEsyK-PeKUEiDacXwkcZG9_wQ
      - DBConnectionString=Server=labs-dbservices01.ucab.edu.ve;Database=GruasUcabOrderMS;Port=5432;User Id=gmartinez;Password=123456
      - ServiosUrl__MsProviders=http://ec2-18-218-238-95.us-east-2.compute.amazonaws.com:5039/locations
      - ServiosUrl__Google=https://maps.googleapis.com/maps/api/
      - ServiosUrl__MsUsers=http://ec2-3-23-105-93.us-east-2.compute.amazonaws.com:5163/send-notification-order
      - ServiosUrl__MsProvidersBase=http://ec2-18-218-238-95.us-east-2.compute.amazonaws.com:5039
      - ServiosUrl__MsUserBase=http://ec2-3-23-105-93.us-east-2.compute.amazonaws.com:5163

    networks:
      - mynetwork
    
    command: >
      sh -c "dotnet ef database update --no-build && dotnet GruasUcabOrdersMS.dll"

networks:
  mynetwork:
    driver: bridge